site_name: "DroneSploit - A Metasploit-like console for hacking drones"
repo_url: https://github.com/dhondta/dronesploit
site_author: dhondta
docs_dir: docs
pages:
  - Introduction: index.md
  - 'Quick Start': quickstart.md
  - 'New Modules': newmodules.md
  - Scenarios: scenario.md
  - Scenarios:
    - 'Hobbico C-me - Changing SSID': scenarios/hobbico-cme.md
    - 'Hobbico Flitt - Power Off': scenarios/hobbico-flitt.md
    - 'DJI Tello - Landing': scenarios/dji-tello.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
extra_javascript:
  - js/collapsible-navbar.js
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.details
  - toc:
      permalink: True
